
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function Order_items() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>Order_items資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.order_items (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        order_id int8 NOT NULL,
                                        print_items_id int8 NOT NULL,
                                        order_sample_img_url text NULL,
                                        order_sample_img_id text NULL,
                                        quantity int4 DEFAULT 1 NOT NULL,
                                        support_thickness int4 NULL,
                                        support_density int4 NULL,
                                        wall_thickness int4 NULL,
                                        lead_time_type varchar NOT NULL,
                                        start_date date NOT NULL,
                                        CONSTRAINT order_items_check CHECK (((lead_time_type)::text = ANY ((ARRAY['slow'::character varying, 'normal'::character varying, 'urgent'::character varying])::text[]))),
                                        CONSTRAINT order_items_pk PRIMARY KEY (id)
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`CREATE INDEX order_items_id_idx ON public.order_items USING btree (id);
                                        CREATE INDEX order_items_order_id_idx ON public.order_items USING btree (order_id);

                                        -- public.order_items foreign keys

                                        ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_list_fk FOREIGN KEY (order_id) REFERENCES public.order_list(id);
                                        ALTER TABLE public.order_items ADD CONSTRAINT order_items_print_items_fk FOREIGN KEY (print_items_id) REFERENCES public.print_items(id);
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}