
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援

import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function DBeaverSettings() {

    

  return (
    <div className="container">
        <div className="content-box">
            <h4>DBeaver建立資料表設定</h4>
            <p>假設希望在DBeaver建立以下同效果的資料表</p>
            <pre className="language-html m-0 p-16">
              <code className="language-html">
                {   dedent(
                        `-- carts: 購物車
                        CREATE TABLE public.carts (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        --資料型別BIGINT
                        --GENERATED BY DEFAULT AS IDENTITY PostgreSQL 產生自動編號的方式
                        --AS IDENTITY 這是一個「自動生成序號」欄位
                        --BY DEFAULT 預設會自動產生數值
                        user_id     BIGINT NOT NULL,
                        status      VARCHAR(20) NOT NULL DEFAULT 'active',
                        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
                        );`
                    )   
                }       
              </code>
            </pre>
            <p>首先在DBeaver資料庫中新建資料表</p>
            <div>
                <img src="images/dbeaver/01.png" alt="" />
            </div>
            <p>修改資料表名稱</p>
            <div>
                <img src="images/dbeaver/02.png" alt="" />
            </div>
            <p>建立資料表內容</p>
            <div>
                <img src="images/dbeaver/03.png" alt="" />
            </div>
            <br />
            <p>Name:欄位名稱</p>
            <p>資料類型:欄位的型別</p>
            <p>
                整數：int、bigint<br />
                文字：varchar(50)、text<br />
                時間：timestamptz<br />
            </p>
            <p>等效資料庫指令:VARCHAR(50)(範例)</p>
            <br />
            <p>身分:是否為「自動流水號欄位」</p>
            <p> - 空白 = 普通欄位<br />
                - By Default = 預設自動生成，但允許手動給值<br />
                - Always = 永遠自動生成，不允許手動給值
            </p>
            <p>等效資料庫指令:GENERATED BY DEFAULT AS IDENTITY 或 GENERATED ALWAYS AS IDENTITY</p>
            <br />
            <p>整理:排序規則</p>
            <p> 數字欄位 → 保持空白<br />
                文字欄位 → 一般用 default<br />
                特殊情境才選 zh_TW.utf8、en_US.utf8 等
            </p>
            <p>等效資料庫指令:COLLATE "zh_TW.utf8"</p>
            <br />
            <p>是否為空:欄位是否能是 NULL</p>
            <p>
                預設允許 NULL<br />
                若必填 → 勾選「不可為空」
            </p>
            <p>等效資料庫指令:NOT NULL</p>
            <br />
            <p>預設:欄位的預設值</p>
            <p> 文字：'active'<br />
                時間：now()<br />
                數字：0
            </p>
            <p>等效資料庫指令:DEFAULT 'active'(範例)</p>
            <br />
            <p>Storage:文字型別的儲存方式</p>
            <p>通常留空（使用預設 EXTENDED）</p>
            <p>等效資料庫指令:STORAGE EXTENDED(範例)</p>
            <br />
            <p>Unique:主鍵/唯一設定</p>
            <p>設定主鍵 (Primary Key)或唯一 (Unique)</p>
            <p> 等效資料庫指令:<br />
                主鍵指令:PRIMARY KEY 或 UNIQUE NOT NULL<br />
                唯一指令:UNIQUE</p>
            <br />
            <p>而索引的部分為以下內容</p>
            <pre className="language-html m-0 p-16">
              <code className="language-html">
                {   dedent(
                    `-- 外鍵到 users（請確認 users 表與型別對齊）
                    ALTER TABLE public.carts
                    ADD CONSTRAINT carts_user_fk
                    --增加約束名為carts_user_fk
                    FOREIGN KEY (user_id) REFERENCES public.users(id);
                    --將user_id設為外鍵並與users資料表的id欄位連結

                    -- 狀態限制
                    ALTER TABLE public.carts
                    ADD CONSTRAINT carts_status_chk
                    --增加約束名為carts_status_chk
                    CHECK (status IN ('active','converted','abandoned','deleted'));
                    --限制status欄位只能出現'active','converted','abandoned','deleted'四種內容其中之一

                    -- （選用）同一使用者同時只允許一個 active 購物車
                    CREATE UNIQUE INDEX uniq_active_cart_per_user
                    --建立唯一索引(UNIQUE Index)名為uniq_active_cart_per_user
                    ON public.carts(user_id)
                    --作用於user_id欄位
                    WHERE status = 'active';
                    --且只對status為'active'的欄位生效

                    -- 常用索引：依 user 查 cart、依 user+status 查 active cart
                    CREATE INDEX idx_carts_user ON public.carts(user_id);
                    --建立一般索引名為idx_carts_user作用於user_id欄位
                    CREATE INDEX idx_carts_user_status ON public.carts(user_id, status);
                    --建立一般索引名為idx_carts_user_status作用於user_id跟status欄位`
                    )   
                }       
              </code>
            </pre>
            <p>首先是外鍵carts_user_fk</p>
            <p>先選擇目標的資料表</p>
            <p>接著選擇目標資料表的外鍵連接欄位</p>
            <p>最後在選擇自己資料表中要連接外鍵的欄位</p>
            <p>這樣外鍵索引就建立完成了</p>
            <div>
                <img src="images/dbeaver/04.png" alt="" />
            </div>
            <p>接著是約束carts_status_chk</p>
            <p>首先是約束的名稱</p>
            <p>接著選擇約束的種類</p>
            <p>最後填寫約束的內容</p>
            <p>這樣約束就建立完成了</p>
            <div>
                <img src="images/dbeaver/05.png" alt="" />
            </div>
            <p>接著是唯一索引uniq_active_cart_per_user</p>
            <p>首先是勾選唯一選項</p>
            <p>接著選擇作用的欄位</p>
            <p>在點擊ok後由外部重新取名</p>
            <p>而WHERE status = 'active';的部分需要在save後選擇open editor後在進行追加</p>
            <p>這樣唯一索引就建立完成了</p>
            <div>
                <img className='d-block' src="images/dbeaver/06.png" alt="" />
                <br />
                <img className='d-block' src="images/dbeaver/07.png" alt="" />
                <br />
                <img className='d-block' src="images/dbeaver/08.png" alt="" />
            </div>
            <p>而idx_carts_user跟idx_carts_user_status普通索引只要不點擊唯一選項即可</p>
        </div>
    </div>
  );
}