
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function Order_list() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>Order_list資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.order_list (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        user_id int8 NOT NULL,
                                        created_at timestamptz DEFAULT now() NOT NULL,
                                        updated_at timestamptz DEFAULT now() NOT NULL,
                                        CONSTRAINT order_list_pk PRIMARY KEY (id)
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`CREATE INDEX order_list_id_idx ON public.order_list USING btree (id);
                                        CREATE INDEX order_list_user_id_idx ON public.order_list USING btree (user_id);

                                        -- public.order_list foreign keys

                                        ALTER TABLE public.order_list ADD CONSTRAINT order_list_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}