
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function User_Profiles() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>User_Profiles資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.user_profiles (
                                        salutation text NULL,
                                        last_name text NULL,
                                        first_name text NULL,
                                        birth_year int4 NULL,
                                        birth_month int4 NULL,
                                        birth_day int4 NULL,
                                        phone text NULL,
                                        mobile text NULL,
                                        country_code text NULL,
                                        postal_code text NULL,
                                        address_line text NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        user_list_id int8 NOT NULL,
                                        CONSTRAINT user_profiles_birth_parts_chk CHECK ((((birth_year IS NULL) AND (birth_month IS NULL) AND (birth_day IS NULL)) OR (((birth_year >= 1900) AND (birth_year <= (EXTRACT(year FROM now()))::integer)) AND ((birth_month >= 1) AND (birth_month <= 12)) AND ((birth_day >= 1) AND (birth_day <= 31)) AND (make_date(birth_year, birth_month, birth_day) <= CURRENT_DATE)))),
                                        CONSTRAINT user_profiles_country_code_chk CHECK (((country_code IS NULL) OR (country_code ~ '^[A-Z]{2}$'::text))),
                                        CONSTRAINT user_profiles_mobile_chk CHECK (((mobile IS NULL) OR (mobile ~ '^(09\d{8}|\+?8869\d{8})$'::text))),
                                        CONSTRAINT user_profiles_phone_chk CHECK (((phone IS NULL) OR (phone ~ '^[0-9\-\+\(\) ]{6,}$'::text))),
                                        CONSTRAINT user_profiles_pk PRIMARY KEY (id),
                                        CONSTRAINT user_profiles_postal_code_chk CHECK (((postal_code IS NULL) OR (postal_code ~ '^\d{3}(\d{2})?$'::text))),
                                        CONSTRAINT user_profiles_salutation_chk CHECK (((salutation = ANY (ARRAY['先生'::text, '女士'::text])) OR (salutation IS NULL)))
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`-- public.user_profiles foreign keys

                                        ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_user_list_fk FOREIGN KEY (user_list_id) REFERENCES public.user_list(id);
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}