
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function Carts_items() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>Carts_items資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.cart_items (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        cart_id int8 NOT NULL,
                                        quantity int4 DEFAULT 1 NOT NULL,
                                        added_at timestamptz DEFAULT now() NOT NULL,
                                        updated_at timestamptz DEFAULT now() NOT NULL,
                                        unit_price numeric(12, 2) NOT NULL,
                                        CONSTRAINT cart_items_pk PRIMARY KEY (id),
                                        CONSTRAINT cart_items_price_chk CHECK ((unit_price >= (0)::numeric)),
                                        CONSTRAINT cart_items_quantity_chk CHECK ((quantity > 0))
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`CREATE INDEX idx_cart_items_cart ON public.cart_items USING btree (cart_id);

                                        -- public.cart_items foreign keys

                                        ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_fk FOREIGN KEY (cart_id) REFERENCES public.carts_list(id) ON DELETE CASCADE;
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}