
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function User_list() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>User_list資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.user_list (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        user_id int8 NOT NULL,
                                        created_at timestamptz DEFAULT now() NOT NULL,
                                        updated_at timestamptz DEFAULT now() NOT NULL,
                                        CONSTRAINT user_list_pk PRIMARY KEY (id)
                                    );
                                    
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`CREATE UNIQUE INDEX user_list_user_id_idx ON public.user_list USING btree (user_id);

                                        -- public.user_list foreign keys

                                        ALTER TABLE public.user_list ADD CONSTRAINT user_list_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}