
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function Print_items() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>Print_items資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`CREATE TABLE public.print_items (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        technique varchar NOT NULL,
                                        material varchar NOT NULL,
                                        color varchar NOT NULL,
                                        "name" varchar NOT NULL,
                                        CONSTRAINT print_items_pk PRIMARY KEY (id)
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後加入資料</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`INSERT INTO public.print_items (technique, material, color, name) VALUES
                                        ('3D列印', 'PLA聚乳酸', '白', '3D列印-PLA聚乳酸-白'),
                                        ('3D列印', 'PLA聚乳酸', '透明', '3D列印-PLA聚乳酸-透明'),
                                        ('3D列印', 'PLA聚乳酸', '黑', '3D列印-PLA聚乳酸-黑'),
                                        ('光固化', '光固化樹脂', '黑', '光固化-光固化樹脂-黑'),
                                        ('光固化', '光固化樹脂', '白', '光固化-光固化樹脂-白'),
                                        ('光固化', '光固化樹脂', '透明', '光固化-光固化樹脂-透明');
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}