
import 'prismjs/themes/prism-tomorrow.css'; // 主題樣式
import Prism from 'prismjs';                // 核心功能
import 'prismjs/components/prism-jsx';      // JSX 支援
import 'prismjs/components/prism-markup';   // HTML 支援
import dedent from 'dedent';//去除多餘空白保持縮排格式


export default function Users() {

    return (
        <>
           <div className="container">
                <div className="title-box">
                    <h2>user資料表構創建 & 設定</h2>
                </div>
                <br />
                <div className="content-box">
                    <p>建立資料表</p>
                    <p>要先建立最核心的會員資料表</p>
                    <pre className="language-html m-0 p-16">
                    <code className="language-html">
                        {   
                            dedent(`-- 可選：做 email 大小寫不敏感唯一時會用到
                                    CREATE EXTENSION IF NOT EXISTS citext;
                                    --EXTENSION是指在資料庫中安裝套件
                                    --citext套件效果是忽略大小寫如"Andy" 與 "andy" 視為相同
                                    --如果資料庫中沒有citext套件就安裝citext，如果有的話就忽略這指令

                                    CREATE TABLE public.users (
                                    --創建一個users資料表在public群組中
                                    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 使用自增 id
                                    --BIGINT 8位元整數
                                    --GENERATED BY DEFAULT AS IDENTITY 平常自動產生id
                                    --PRIMARY KEY 主鍵約束自動建立唯一索引
                                    username          VARCHAR(50), 
                                    --VARCHAR(50)文字型態限制最大長度50
                                    email             CITEXT,                  
                                    -- CITEXT 無視大小寫且本身就帶有text型態
                                    password          TEXT,                    
                                    -- 儲存「雜湊」後的密碼（不是明碼）
                                    role              VARCHAR(20) DEFAULT 'user', 
                                    -- 'admin' | 'user' | 'vip' | 'vendor'
                                    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
                                    -- TIMESTAMPTZ帶有時區的時間點
                                    -- NOT NULL 不可為空
                                    -- 預設資料為現在時間點
                                    google_id         TEXT,                    
                                    -- Google OAuth 的 sub/id
                                    auth_provider     VARCHAR(20) NOT NULL DEFAULT 'local', 
                                    -- 'local' | 'google'
                                    avatar_url        TEXT,                    
                                    -- 圖片完整網址
                                    avatar_public_id  TEXT                     
                                    -- 圖片 public_id（例如 userAvatars/xxxx）
                                    );
                                `
                            )   
                        }       
                    </code>
                    </pre>
                    <p>資料表建立完成後要加入約束跟限制</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`BEGIN;
                                        --BEGIN;代表開始 
                                        --COMMIT;代表結束
                                        --中間過程一但有錯誤就會整個跳出且已經完成的程序都不會生效
                                        --要一路到結束都完成程序才會生效

                                        -- 1) email 不可為空 & 唯一（你已用 CITEXT，天然大小寫不敏感）
                                        ALTER TABLE public.users
                                        --ALTER 代表修改
                                        ALTER COLUMN email SET NOT NULL,
                                        --COLUMN代表欄位
                                        --ALTER COLUMN email SET NOT NULL,
                                        --代表修改欄位email為不可空白
                                        ADD CONSTRAINT users_email_uniq UNIQUE (email);
                                        --CONSTRAINT代表加入約束
                                        --users_email_uniq 為 給約束取的名稱
                                        --UNIQUE代表不能有相同的數值，效果為唯一「約束」
                                        --加入一個約束，取名為users_email_uniq，使用UNIQUE類型的約束，作用於email欄位

                                        -- 2) 角色值限制（admin / user / vip / vendor）
                                        ALTER TABLE public.users
                                        ADD CONSTRAINT users_role_chk
                                        --加入約束，取名為users_role_chk
                                        CHECK (role IN ('admin','user','vip','vendor'));
                                        --使用CHECK類型的約束，用來限制欄位可接受的值
                                        --限定role欄位的數值必須是'admin','user','vip','vendor'其中一個
                                        
                                        -- 3) 登入來源限制（local / google）
                                        ALTER TABLE public.users
                                        ADD CONSTRAINT users_auth_provider_chk
                                        --加入約束，取名為users_auth_provider_chk
                                        CHECK (auth_provider IN ('local','google'));
                                        --使用CHECK類型的約束，用來限制欄位可接受的值
                                        --限定auth_provider欄位的數值必須是'local','google'其中一個

                                        -- 4) 來源與欄位對應邏輯
                                        -- local：必須有 password，且 google_id 必須為 NULL
                                        -- google：必須有 google_id，且 password 必須為 NULL
                                        ALTER TABLE public.users
                                        ADD CONSTRAINT users_provider_fields_chk
                                        --加入約束，取名為users_provider_fields_chk
                                        CHECK (
                                            (auth_provider = 'local'  AND password IS NOT NULL AND google_id IS NULL)
                                        OR (auth_provider = 'google' AND google_id IS NOT NULL AND password IS NULL)
                                        );
                                        --限定auth_provider欄位的數值如果是'local'則password欄位不能為空且google_id必須為空
                                        --限定auth_provider欄位的數值如果是'google'則password欄位必須為空且google_id必須不為空

                                        -- 5) google_id 在非 NULL 時必須唯一（允許多個 NULL）
                                        CREATE UNIQUE INDEX users_google_id_uniq_notnull
                                        --建立一個唯一索引UNIQUE INDEX，名稱為users_google_id_uniq_notnull
                                        --唯一索引是加速搜尋用的跟UNIQUE約束是不同的兩個東西
                                        --作用於google_id欄位
                                        ON public.users (google_id)
                                        WHERE google_id IS NOT NULL;
                                        --只有在google_id欄位數值不為空時唯一索引才起作用

                                        -- 6) created_at 不可為空且預設現在（保險補上）
                                        ALTER TABLE public.users
                                        ALTER COLUMN created_at SET NOT NULL,
                                        --修改欄位created_at 限制不可為空
                                        ALTER COLUMN created_at SET DEFAULT now();
                                        --修改欄位created_at 限制預設為現在時間

                                        -- 7) 頭像欄位一致性（要嘛兩個都有，要嘛兩個都為 NULL）
                                        ALTER TABLE public.users
                                        ADD CONSTRAINT users_avatar_pair_chk
                                        --加入約束，名稱為users_avatar_pair_chk
                                        CHECK (
                                            (avatar_url IS NULL AND avatar_public_id IS NULL)
                                        OR (avatar_url IS NOT NULL AND avatar_public_id IS NOT NULL)
                                        );
                                        --限定avatar_url欄位為空時avatar_public_id也要為空
                                        --限定avatar_url欄位不為空時avatar_public_id也要不為空

                                        COMMIT;
                                    `
                                )   
                            }       
                        </code>
                    </pre>
                    <p>索引跟約束也加入以後資料表就建立完成了<br />
                    為了方面操作可以先建立一個管理員在資料表內部</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
	                                    --資料庫中如果沒有pgcrypto(加密套件)就建立(CREATE)並載入(EXTENSION)如果有則忽略此操作`
                                )   
                            }       
                        </code>
                    </pre>
                    <p>先在目標資料庫啟用一次 pgcrypto接著再插入管理員資訊</p>
                    <p>帳號admin123<br />
                    信箱admin123@gmail.com<br />
                    密碼admin123</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`INSERT INTO public.users
                                        --新增資料於資料表users
                                        (username, email, password, role, auth_provider, google_id, avatar_url, avatar_public_id)
                                        VALUES
                                        ('admin123', 'admin123@gmail.com',
                                        crypt('admin123', gen_salt('bf', 10)),
                                        'admin', 'local', NULL, NULL, NULL);`
                                )   
                            }       
                        </code>
                    </pre>
                    <p>如果這時候想對資料表的欄位變動的話</p>
                    <p>如以下操作</p>
                    <p>移除avatar_url跟avatar_public_id再加入aaa方法如下</p>
                    <pre className="language-html m-0 p-16">
                        <code className="language-html">
                            {   
                                dedent(`BEGIN;

                                        -- 1) 先移除跟頭像欄位相關的 CHECK 約束，否則無法 DROP 欄位
                                        ALTER TABLE public.users
                                        DROP CONSTRAINT IF EXISTS users_avatar_pair_chk;
                                        --DROP CONSTRAINT 的意思是 移除一個已經存在於資料表上的「約束 (constraint)」
                                        --如果users_avatar_pair_chk這個約束存在就移除否則就忽略
                                        -- 2) 移除頭像兩個欄位
                                        ALTER TABLE public.users
                                        DROP COLUMN IF EXISTS avatar_url,
                                        --DROP COLUMN 移除欄位
                                        DROP COLUMN IF EXISTS avatar_public_id;

                                        -- 3) 新增 aaa 欄位（型別示範用 TEXT；你可改成 VARCHAR(50) / BOOLEAN / INTEGER 等）
                                        ALTER TABLE public.users
                                        ADD COLUMN IF NOT EXISTS aaa TEXT;
                                        --ADD COLUMN 新增欄位

                                        -- (選擇性) 如果 aaa 需要限制，這裡加：
                                        -- 例如唯一：
                                        -- ALTER TABLE public.users ADD CONSTRAINT users_aaa_uniq UNIQUE (aaa);
                                        -- 例如非空 + 預設值：
                                        -- ALTER TABLE public.users ALTER COLUMN aaa SET NOT NULL;
                                        -- ALTER TABLE public.users ALTER COLUMN aaa SET DEFAULT 'init';

                                        COMMIT;`
                                )   
                            }       
                        </code>
                    </pre>
                </div>
            </div>
        </>
    );
}